### ISSUE TITLE
Manifest generation crashing for simple Gotham Knights mod UTOC (UE 4.25 Plus)

### ISSUE THREAD

**Issue by peek6** [gitMenv/UEcastoc#17]
Fantastic tool!  I've been trying to get it working for Gotham Knights, which uses UE 4.25 Plus and switched to using IoStore as of the Feb 14 update to the game.  I made a very simple mod in UE 4.25plus which works in game ( [IOSTORE_VERSION_chunk101_robin_metal_mask_on_knightwatch_suit.zip](https://github.com/gitMenv/UEcastoc/files/10994805/IOSTORE_VERSION_chunk101_robin_metal_mask_on_knightwatch_suit.zip) or can be grabbed from here <a href="https://www.nexusmods.com/gothamknights/mods/278?tab=files&file_id=881">https://www.nexusmods.com/gothamknights/mods/278?tab=files&file_id=881</a> ). Unpacking the mod with your tool complains that the TOC isn't supported, but the unpacking operation nevertheless works well:

```
PS D:\games\tools\uecastoc_2023_031_git\UEcastoc\cpp> .\main.exe unpackAll .\z_chunk101_robin_metal_mask_on_knightwatch_suit_P.utoc .\z_chunk101_robin_metal_mask_on_knightwatch_suit_P.ucas output\
Warning: this is a version of the utoc file format that may not be supported yet
number of unpacked files:2

```
The manifest generation crashes, though:

```
PS D:\games\tools\uecastoc_2023_031_git\UEcastoc\cpp> .\main.exe manifest .\z_chunk101_robin_metal_mask_on_knightwatch_suit_P.utoc .\z_chunk101_robin_metal_mask_on_knightwatch_suit_P.ucas manifest.json
Warning: this is a version of the utoc file format that may not be supported yet
panic: runtime error: index out of range [227290525] with length 149284656

goroutine 17 [running, locked to thread]:
main.(*parseDependencies).extractDependencies(0xc000194180)
        D:/games/tools/uecastoc_2023_031_git/UEcastoc/manifest.go:118 +0x328
main.ParseDependencies({0xc00027a000, 0x33b36, 0x40000})
        D:/games/tools/uecastoc_2023_031_git/UEcastoc/manifest.go:239 +0x5d5
main.(*UTocData).constructManifest(0xc00001f1e0, {0xc00000e580, 0x38})
        D:/games/tools/uecastoc_2023_031_git/UEcastoc/manifest.go:90 +0xe7
main.createManifestFile(0x7ffa20a16e98, 0xc00001a060, 0x0, 0x1)
        D:/games/tools/uecastoc_2023_031_git/UEcastoc/dllAPI.go:137 +0x407
```

And I can't try re-packing since I can't get a manifest.

Anyway, thanks again for making this tool!

**Comment by Phnxsmv** [comment]
UEcastoc does not work for Gotham Knights mods, unpacking and creating a manifest. It may have something to do with UE 4.25 Plus IO Store files containing cooked assets that are split into uasset and uexp files. While UE 4.27.2 IO Store files contain only uasset files. I get index out of range errors with Gotham Knights files. Maybe that's because there are twice as many files in the archives?
